#pragma config(Sensor, in1,    liftAngle,      sensorPotentiometer)
#pragma config(Motor,  port1,           backRightMotor, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backLeftMotor, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           frontRightMotor, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeftMotor, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           rightArmY,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rightArmB,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           leftArmY,      tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftArmB,      tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           sideDrive,     tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Arm at floor level = 55
   Maximum height 2416
   Soft stop at 2300
   Carry = 400
*/
void Arm(int rArmY, int rArmB, int lArmY, int lArmB)
{
	motor[rightArmY] = rArmY;
	motor[rightArmB] = rArmB;
	motor[leftArmY] = lArmY;
	motor[leftArmB] = lArmB;
	wait1Msec(25);
}


task main()
{

while(true)
	{

	//drive train
	motor[frontLeftMotor] = vexRT[Ch3];
	motor[backLeftMotor] = vexRT[Ch3];
	motor[frontRightMotor] = vexRT[Ch2];
	motor[backRightMotor] = vexRT[Ch2];
	motor[sideDrive] = vexRT[Ch1];
	//arm controls

	if((vexRT[Btn6U] == 1)&&(SensorValue[liftAngle] < 2300)){
		Arm(127,127,127,127);
		//motor[rightArmY] = 127;
		//motor[rightArmB] = 127;
		//motor[leftArmY] = 127;
		//motor[leftArmB] = 127;
		}
	else if((vexRT[Btn6U] == 1)&&(SensorValue[liftAngle] > 2300)){
		motor[rightArmY] = 0;
		motor[rightArmB] = 0;
		motor[leftArmY] = 0;
		motor[leftArmB] = 0;
		}
	else if((vexRT[Btn6D] == 1)&& (SensorValue[liftAngle] > 50)){
		motor[rightArmY] = -100;
		motor[rightArmB] = -100;
		motor[leftArmY] =  -100;
		motor[leftArmB] =  -100;
		}
	else if((vexRT[Btn6D] == 1)&& (SensorValue[liftAngle] < 50)){
		motor[rightArmY] = 0;
		motor[rightArmB] = 0;
		motor[leftArmY] =  0;
		motor[leftArmB] =  0;
		}
	else
		{
			motor[rightArmY] = 10;
			motor[rightArmB] = 10;
			motor[leftArmY] =  10;
			motor[leftArmB] =  10;
		}
		/*
		else if(vexRT[Btn6U] == 0){
		motor[rightArmY] = 5;
		motor[rightArmB] = 5;
		motor[leftArmY] =  5;
		motor[leftArmB] =  5;
		}

	else if(vexRT[Btn6D] == 0){
		motor[rightArmY] = 5;
		motor[rightArmB] = 5;
		motor[leftArmY] =  5;
		motor[leftArmB] =  5;
		}
*/
 if((vexRT[Btn8L] == 1) && (SensorValue[liftAngle] > 60)){
    motor[rightArmY] = -100;
		motor[rightArmB] = -100;
		motor[leftArmY] =  -100;
		motor[leftArmB] =  -100;
	waitUntil(SensorValue[liftAngle] <= 60);
		motor[rightArmY] = 0;
		motor[rightArmB] = 0;
		motor[leftArmY] =  0;
		motor[leftArmB] =  0;
	}

	if((vexRT[Btn8U] == 1) && (SensorValue[liftAngle] > 400)){
    motor[rightArmY] = -100;
		motor[rightArmB] = -100;
		motor[leftArmY] =  -100;
		motor[leftArmB] =  -100;
		waitUntil(SensorValue[liftAngle] < 400);
		motor[rightArmY] = 0;
		motor[rightArmB] = 0;
		motor[leftArmY] =  0;
		motor[leftArmB] =  0;
	}
	else if((vexRT[Btn8U] == 1) && (SensorValue[liftAngle] < 400)){
    motor[rightArmY] = 100;
		motor[rightArmB] = 100;
		motor[leftArmY] =  100;
		motor[leftArmB] =  100;
		waitUntil(SensorValue[liftAngle] > 400);
		motor[rightArmY] = 0;
		motor[rightArmB] = 0;
		motor[leftArmY] =  0;
		motor[leftArmB] =  0;
	}

	wait1Msec(25);
	}

}

task pidLiftControl(){

	float pidSensorCurrentValue;
 	float pidError;
 	float pidDrive;

}
