#pragma config(Sensor, in1,    armAngle,       sensorPotentiometer)
#pragma config(Sensor, in2,    batmanAngle,    sensorPotentiometer)
#pragma config(Motor,  port1,           rightDrive,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           batmanRightDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           batmanLeftDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightArmY,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           leftArmY,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           topRight,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           bottomRight,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           topLeft,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           bottomLeft,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftDrive,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// low is 4000
//hight is 1800
// batman low is 150
//batman high is 2200

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!



/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

while(true)
	{
		motor[leftDrive] = vexRT[Ch3];
		motor[rightDrive] = vexRT[Ch2];

		if (vexRT[Btn6U] == 1 && SensorValue[armAngle] > 1800) {
			motor[topLeft] = 100;
			motor[bottomLeft] = 100;
			motor[topRight] = 100;
			motor[bottomRight] = 100;
		}

		else if (vexRT[Btn6D] == 1 && SensorValue[armAngle] < 4000) {
			motor[topLeft] = -100;
			motor[bottomLeft] = -100;
			motor[topRight] = -100;
			motor[bottomRight] = -100;
		}

		else {
			motor[topLeft] = 10;
			motor[bottomLeft] = 10;
			motor[topRight] = 10;
			motor[bottomRight] = 10;
		}



		motor[batmanLeftDrive] = vexRT[Ch3Xmtr2];
		motor[batmanRightDrive] = vexRT[Ch2Xmtr2];

		if (vexRT[Btn6UXmtr2] == 1 && SensorValue[batmanAngle] < 2200) {
			motor[leftArmY] = 100;
			motor[rightArmY] = 100;
		}

		else if (vexRT[Btn6DXmtr2] == 1 && SensorValue[batmanAngle] > 150) {
			motor[leftArmY] = -100;
			motor[rightArmY] = -100;
		}

		else {
			motor[leftArmY] = 10;
			motor[rightArmY] = 10;
		}
		SensorValue[batmanAngle] = 0;
		wait1Msec(25);
	}
}
