#pragma config(Sensor, in1,    armAngle,       sensorPotentiometer)
#pragma config(Sensor, in2,    batmanAngle,    sensorPotentiometer)
#pragma config(Motor,  port1,           rightDrive,    tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           batmanRightDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           batmanLeftDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontRightDrive, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           frontLeftDrive, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           topRight,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           bottomRight,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           topLeft,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           bottomLeft,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftDrive,     tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// robin low is 4000
//robin hight is 1800
// batman low is 150
//batman high is 2200

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
/*
void batmanDrive(int leftD, int rightD){
	motor[batmanLeftDrive] = leftD;
	motor[batmanRightDrive] = rightD;
}
*/
void robinDrive(int leftD, int rightD){
	motor[leftDrive] = leftD;
	motor[rightDrive] = rightD;
	motor[frontLeftDrive] = leftD;
	motor[frontRightDrive] = rightD;
}
/*
void batmanArm(int lArm, int rArm) {
	motor[leftArmY] = lArm;
	motor[rightArmY] = rArm;
}
*/
void robinArm(int tL, int bL, int tR, int bR) {
	motor[topLeft] = tL;
	motor[bottomLeft] = bL;
	motor[topRight] = tR;
	motor[bottomRight] = bR;
}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
 //open batman and let robin out
	//batmanArm(70, 70);
	//waitUntil(SensorValue[batmanAngle] >= 1700);
	//batmanArm(10, 10);
 	robinDrive(70, 70);
  wait1Msec(500);
 	robinDrive(-70, -70);
  wait1Msec(300);
  robinDrive(0,0);

	robinArm(70, 70, 70, 70);
	waitUntil(SensorValue[armAngle] <= 2550);
	robinArm(0,0,0,0);

	robinDrive(60, 60);
	wait1Msec(2500);
	robinDrive(0, 0);

//	batmanDrive(35,-35);
	robinDrive(-100,-100);
	wait1Msec(750);
//	batmanDrive(0,0);
	robinDrive(0,0);

	/*batmanArm(-20,-20);
	waitUntil(SensorValue[batmanAngle]<= 500);
	batmanArm(0,0);


	batmanDrive(100,100);
	wait1Msec(1750);
	batmanDrive(0,0);*/

	//AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

while(true)
	{
		motor[leftDrive] = vexRT[Ch3]/1.5;
		motor[rightDrive] = vexRT[Ch2]/1.5;
		motor[frontLeftDrive] = vexRT[Ch3]/1.5;
		motor[frontRightDrive] = vexRT[Ch2]/1.5;

		if (vexRT[Btn6U] == 1 && SensorValue[armAngle] > 1800) {
			motor[topLeft] = 100;
			motor[bottomLeft] = 100;
			motor[topRight] = 100;
			motor[bottomRight] = 100;
		}

		else if (vexRT[Btn6D] == 1 && SensorValue[armAngle] < 4100) {
			motor[topLeft] = -100;
			motor[bottomLeft] = -100;
			motor[topRight] = -100;
			motor[bottomRight] = -100;
		}

		else {
			motor[topLeft] = 10;
			motor[bottomLeft] = 10;
			motor[topRight] = 10;
			motor[bottomRight] = 10;
		}


/*
		motor[batmanLeftDrive] = vexRT[Ch3Xmtr2];
		motor[batmanRightDrive] = vexRT[Ch2Xmtr2];

		if (vexRT[Btn6UXmtr2] == 1 && SensorValue[batmanAngle] < 2400) {
			motor[leftArmY] = 100;
			motor[rightArmY] = 100;
		}

		else if (vexRT[Btn6DXmtr2] == 1 && SensorValue[batmanAngle] > 150) {
			motor[leftArmY] = -100;
			motor[rightArmY] = -100;
		}

		else {
			motor[leftArmY] = 10;
			motor[rightArmY] = 10;
		}
		SensorValue[batmanAngle] = 0;
		wait1Msec(25);*/
	}
}
