#pragma config(Motor,  port5,           bottomRight,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           topRight,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           bottomLeft,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           topLeft,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		if (vexRT[Btn6U] == 1) {
			motor[topLeft] = 100;
			motor[bottomLeft] = 100;
			motor[topRight] = 100;
			motor[bottomRight] = 100;
		}

		else if (vexRT[Btn6D] == 1) {
			motor[topLeft] = -100;
			motor[bottomLeft] = -100;
			motor[topRight] = -100;
			motor[bottomRight] = -100;
		}

		else {
			motor[topLeft] = 10;
			motor[bottomLeft] = 10;
			motor[topRight] = 10;
			motor[bottomRight] = 10;
		}
		wait1Msec(25);

	}


}
