#pragma config(Sensor, in1,    armAngle,       sensorPotentiometer)
#pragma config(Motor,  port5,           bottomRight,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           topRight,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           bottomLeft,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           topLeft,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftDrive,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// low is 2700
//hight is 500
task main()
{
	while(true) {
		motor[leftDrive] = vexRT[Ch3];
		motor[rightDrive] = vexRT[Ch2];

		if (vexRT[Btn6U] == 1 && SensorValue[armAngle] > 500) {
			motor[topLeft] = 100;
			motor[bottomLeft] = 100;
			motor[topRight] = 100;
			motor[bottomRight] = 100;
		}

		else if (vexRT[Btn6D] == 1 && SensorValue[armAngle] < 2700) {
			motor[topLeft] = -100;
			motor[bottomLeft] = -100;
			motor[topRight] = -100;
			motor[bottomRight] = -100;
		}

		else {
			motor[topLeft] = 10;
			motor[bottomLeft] = 10;
			motor[topRight] = 10;
			motor[bottomRight] = 10;
		}
		wait1Msec(25);

	}


}
